# Generated by Django 3.2.13 on 2022-07-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('market_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jodi', models.IntegerField(max_length=10)),
                ('release_date', models.DateField()),
                ('panel', models.IntegerField(max_length=10)),
                ('card', models.IntegerField(max_length=10)),
                ('market_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.markets')),
            ],
        ),
    ]
